name: Build Resume

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build with Docker
        run: |
          docker build -t resume-builder .
          docker run --rm -v ${{ github.workspace }}:/data resume-builder

      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: resume-outputs
          path: |
            Resume.pdf

