name: Build Resume

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag name (e.g., v1.0.1)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image and generate resume
        run: |
          docker build -t resume-builder .
          docker run --rm -v ${{ github.workspace }}:/data resume-builder

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: Release ${{ github.event.inputs.release_tag }}
          files: |
            Resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

